// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0X6ADRR-iMsuJKuLUzYs5Wu-MTXWhlI',
    appId: '1:163186978471:web:264757d25d0b282d09b582',
    messagingSenderId: '163186978471',
    projectId: 'restaurant-order-system-cc60f',
    authDomain: 'restaurant-order-system-cc60f.firebaseapp.com',
    storageBucket: 'restaurant-order-system-cc60f.firebasestorage.app',
    measurementId: 'G-TGFV98KBV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzjOpwjfNT_5BW1JWujRXq7bTHQDUEj1k',
    appId: '1:163186978471:android:549e1a428f138c3609b582',
    messagingSenderId: '163186978471',
    projectId: 'restaurant-order-system-cc60f',
    storageBucket: 'restaurant-order-system-cc60f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn0X6ADRR-iMsuJKuLUzYs5Wu-MTXWhlI',
    appId: '1:163186978471:web:213e6ee60937216a09b582',
    messagingSenderId: '163186978471',
    projectId: 'restaurant-order-system-cc60f',
    authDomain: 'restaurant-order-system-cc60f.firebaseapp.com',
    storageBucket: 'restaurant-order-system-cc60f.firebasestorage.app',
    measurementId: 'G-YV3CNTL2SY',
  );
}
