// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEhXZz107WbrhFtYeUgZabMmKPud4H98',
    appId: '1:650925008122:web:4b9a58901adc7b14821543',
    messagingSenderId: '650925008122',
    projectId: 'cloud-notes-app-3fd9e',
    authDomain: 'cloud-notes-app-3fd9e.firebaseapp.com',
    storageBucket: 'cloud-notes-app-3fd9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ko_hZobPUfzd2jsCdsfsAnjuSW8LjJQ',
    appId: '1:650925008122:android:648f905a089b4dee821543',
    messagingSenderId: '650925008122',
    projectId: 'cloud-notes-app-3fd9e',
    storageBucket: 'cloud-notes-app-3fd9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WLfH2cNMn7-dFcTl07pCUR8Y4_wR9-M',
    appId: '1:650925008122:ios:2187bf2456e1ef24821543',
    messagingSenderId: '650925008122',
    projectId: 'cloud-notes-app-3fd9e',
    storageBucket: 'cloud-notes-app-3fd9e.firebasestorage.app',
    iosBundleId: 'com.example.cloudNotesApp',
  );
}
